##############################################################################
##
#X  Rubik's cube 2x2x2
##
println("  Rubik's 2x2x2 cube, as a perm. group on 21 points: ")
println("  -------------------------------------------------- ")
println("           +--------+                                ")
println("           |  1   2 |                                ")
println("           |  3   4 |                                ")
println("  +--------+--------+--------+--------+              ")
println("  |  5   6 |  8   9 | 12  13 | 16  17 |              ")
println("  |  *   7 | 10  11 | 14  15 | 18   * |              ")
println("  +--------+--------+--------+--------+              ")
println("           | 19  20 |                                ")
println("           |  *  21 |                                ")
println("           +--------+                                ")

g = symmetric_group(21)
top   = cperm(g, [[1, 2, 4, 3], [5, 16, 12, 8], [6, 17, 13, 9]])
front = cperm(g, [[8, 9, 11, 10], [3, 12, 20, 7], [4, 14, 19, 6]])
right = cperm(g, [[2, 18, 20, 9], [4, 16, 21, 11], [12, 13, 15, 14]])

cube = sub(g, [top, front, right])[1]

println("")
println("  cube: group generated by rotations of three faces")

##############################################################################
##
#E

