################################################################
#
# O1. Some large numbers
#

# get a list of primes
# GOTCHA: small vs. big integers
#ps = filter(is_prime, 1:1000)
ps = filter(is_prime, ZZ(1):ZZ(1000))
#ps = collect(PrimesSet(ZZ(1), ZZ(1000)))

# compute the number E_n (note that the name "E" is already taken in GAP)
e(n) = prod(ps[1:n])+1
#e(n) = prod(ZZ(ps[1:n]))+1

# for which n is the result a prime?
[n for n in 1:length(ps) if is_prime(e(n))]
filter(n -> is_prime(e(n)), 1:length(ps))



################################################################
#
# O2. Subgroups of the symmetric group
#

# Let G be the group generated by the permutations (1,2,3,...,n) and (1,p),
# for some p. Try several values of n and p: When is G the full symmetric group on n points?

grp1(n,p) = sub(symmetric_group(n), [cperm(1:n), cperm([1,p])])[1]

for n in 1:10, p in 2:n
  is_natural_symmetric_group(grp1(n,p)) && println( (n,p) )
end

# or...
[ (n,p) for n in 1:10 for p in 2:n if is_natural_symmetric_group(grp1(n,p))]


# Replace (1,p) by (1,p,q).
grp3(n,p,q) = group(cperm(1:n), cperm([1,p,q]))

for n in 1:10, p in 2:n, q in p+1:n
  is_natural_symmetric_group(grp3(n,p,q)) && println((n,p,q));
end

# Let G be the group generated by the permutations (1,3,4,...,n) and (1,2,3).
# Try several values of n: When is G the full symmetric group on n points?
grp4(n) = group(perm(vcat([3,2],4:n,[1])), cperm(1:3))

filter(n -> is_natural_symmetric_group(grp4(n)), 3:30)

# verify theory: all odd n >= 3
filter(n -> is_natural_symmetric_group(grp4(n)), 3:30) == 3:2:29


# Replace (1,2,3) by (1,2,3,4).
grp5(n) = group(perm(vcat([3,2],4:n,[1])), cperm(1:4))

filter(n -> is_natural_symmetric_group(grp5(n)), 4:30)

# verify theory: all n >= 4 other than 5
filter(n -> ! is_natural_symmetric_group(grp5(n)), 4:30)


################################################################
#
# O3. An isomorphism
#

G = SL(2,4)
H = alternating_group(5)

is_isomorphic(G, H)

isomorphism(G, H)

S, = sylow_subgroup(G, 2)
N, = normalizer(G, S)
act = right_coset_action(G, N)
is_bijective(act)

U = image(act)[1]
order(U)
degree(U)
is_natural_alternating_group(U)
