################################################################
#
# G1. Some large numbers
#

# get a list of primes (could also use GAP's `Primes`)
ps := Filtered([1..2000], IsPrimeInt);;

# compute the number E_n (note that the name "E" is already taken in GAP)
e := n -> Product(ps{[1..n]})+1;

# alternative solution
e2 := n -> Product([1..n], i -> ps[i])+1;

# another alternative
e3 := function(n)
  local i, res;
  res := 1;
  for i in [1..n] do
    res := res * ps[i];
  od;
  return res + 1;
end;

# for which n is the result a prime?
Filtered([1..Length(ps)], n -> IsPrime(e(n)));



################################################################
#
# G2. Subgroups of the symmetric group
#

# Let G be the group generated by the permutations (1,2,3,...,n) and (1,p),
# for some p. Try several values of n and p: When is G the full symmetric group on n points?

grp1:=function(n,p)
    return Group(PermList(Concatenation([2..n],[1])), (1,p));
end;
#grp1:={n,p} -> Group(CycleFromList([1..n]), (1,p));


for n in [1..10] do
  for p in [2..n] do
    G := grp1(n,p);
    if IsNaturalSymmetricGroup(G) then
        Display([n,p]);
    fi;
  od;
  Print("----\n");
od;

# or...
PrintArray(ListX([1..10],n->[2..n], {n,p}->IsNaturalSymmetricGroup(grp1(n,p)), {n,p}->[n,p]));



# Replace (1,p) by (1,p,q).
grp3:={n,p,q} -> Group(CycleFromList([1..n]), (1,p,q));

for n in [1..10] do
  for p in [2..n] do
    for q in [p+1..n] do
      G := grp3(n,p,q);
      if IsNaturalSymmetricGroup(G) then
          Display([n,p,q]);
      fi;
    od;
  od;
  Print("----\n");
od;


PrintArray(ListX([1..10],n->[2..n],{n,p}->[p+1..n], {n,p,q}->IsNaturalSymmetricGroup(grp3(n,p,q)), {n,p,q}->[n,p,q]));

# Let G be the group generated by the permutations (1,3,4,...,n) and (1,2,3).
# Try several values of n: When is G the full symmetric group on n points?
grp4:=n -> Group(PermList(Concatenation([3,2],[4..n],[1])), (1,2,3));

Filtered([3..30], n -> IsNaturalSymmetricGroup(grp4(n)));

# verify theory: all odd n >= 3
Filtered([3..30], n -> IsOddInt(n) <> IsNaturalSymmetricGroup(grp4(n)));



# Replace (1,2,3) by (1,2,3,4).
grp5:=n -> Group(PermList(Concatenation([3,2],[4..n],[1])), (1,2,3,4));

Filtered([4..30], n -> IsNaturalSymmetricGroup(grp5(n)));

# verify theory: all n >= 4 other than 5
Filtered([4..30], n -> not IsNaturalSymmetricGroup(grp5(n)));



################################################################
#
# G3. An isomorphism
#


G := SL(2,4);
H := AlternatingGroup(5);

IsomorphismGroups(G,H);

S := SylowSubgroup(G, 2);
N := Normalizer(G, S);
act := FactorCosetAction(G,N);;
IsBijective(act);

U := Image(act);
Size(U);
NrMovedPoints(U);
IsNaturalAlternatingGroup(U);
