name: Tutorial Status Script

on:
  pull_request:
  push:
    branches: [gh-pages]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tutorial-status-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub pyyaml requests

      - name: Run Tutorial Status Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: "1"
        run: |
          python3 etc/tutorial_status.py
